workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build iOS (no code sign)
        script: |
          flutter build ios --release --no-codesign

      - name: Create unsigned IPA
        script: |
          set -e
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -R Runner.app Payload/
          zip -r Runner-unsigned.ipa Payload
          mv Runner-unsigned.ipa ../../Runner-unsigned.ipa

    artifacts:
      - build/Runner-unsigned.ipa
