workflows:
  ios-ipa:
    name: iOS IPA Build (unsigned)
    instance_type: mac_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build iOS unsigned .ipa
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
