workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build iOS (no code sign)
        script: |
          flutter build ios --release --no-codesign

      - name: Package IPA
        script: |
          set -e
          mkdir -p build/ios/ipa/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r Runner.ipa Payload
          mv Runner.ipa ../../Runner.ipa
          cd ../../..

    artifacts:
      - build/Runner.ipa
