workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Clean Cocoapods (force reset)
        script: |
          rm -rf ios/Pods
          rm -f ios/Podfile.lock

      - name: Install Pods using CDN
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS (no code sign)
        script: |
          flutter build ios --release --no-codesign

      - name: Package IPA
        script: |
          mkdir -p build/ios/ipa/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r Runner.ipa Payload
          mv Runner.ipa ../../Runner.ipa
          cd ../../..

    artifacts:
      - build/Runner.ipa
