workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      flutter: stable
      xcode: latest
      vars:
        HOMEBREW_NO_AUTO_UPDATE: 1
        HOMEBREW_NO_ANALYTICS: 1
        COCOAPODS_DISABLE_DETERMINISTIC_UUIDS: 1

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/Homebrew
        - ios/Pods
        - ios/Podfile.lock
        - ios/Flutter/Generated.xcconfig
        - ios/build  # Cache DerivedData để tăng tốc

    scripts:
      # 1. CÀI COCOAPODS TỪ HOMEBREW
      - name: Install CocoaPods
        script: |
          brew install cocoapods
          export PATH="/opt/homebrew/bin:$PATH"
          echo "CocoaPods version: $(pod --version)"

      # 2. FLUTTER PUB GET
      - name: Flutter Pub Get
        script: |
          export PATH="/opt/homebrew/bin:$PATH"
          flutter pub get

      # 3. CÀI PODS (CHỈ CHẠY NẾU CHƯA CÓ Podfile.lock)
      - name: Install Pods (Only if needed)
        script: |
          export PATH="/opt/homebrew/bin:$PATH"
          cd ios
          if [ ! -f "Podfile.lock" ]; then
            echo "Podfile.lock not found → Running pod install"
            /opt/homebrew/bin/pod install --verbose
          else
            echo "Podfile.lock exists → Skipping pod install"
          fi
          cd ..

      # 4. BUILD VỚI XCODEBUILD (BỎ QUA FLUTTER TOOLS)
      - name: Build with xcodebuild
        script: |
          export PATH="/opt/homebrew/bin:$PATH"
          cd ios

          echo "Starting xcodebuild..."
          xcodebuild -workspace Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -derivedDataPath build \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO \
                     -quiet

          # Kiểm tra build có thành công không
          if [ $? -ne 0 ]; then
            echo "xcodebuild failed!"
            exit 1
          fi

          cd ..

      # 5. PACKAGE IPA (ĐÃ SỬA ĐƯỜNG DẪN + KIỂM TRA LỖI)
      - name: Package IPA
        script: |
          APP_PATH="ios/build/Build/Products/Release-iphoneos/Runner.app"
          IPA_OUTPUT="build/Runner.ipa"

          # Kiểm tra Runner.app có tồn tại không
          if [ ! -d "$APP_PATH" ]; then
            echo "ERROR: $APP_PATH not found!"
            echo "Listing ios/build/Build/Products/Release-iphoneos/:"
            ls -la ios/build/Build/Products/Release-iphoneos/ || true
            exit 1
          fi

          echo "Found Runner.app → Packaging IPA..."

          # Tạo thư mục
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/

          # Tạo IPA
          zip -r Runner.ipa Payload
          rm -rf Payload

          # Tạo thư mục build và di chuyển IPA
          mkdir -p build
          mv Runner.ipa "$IPA_OUTPUT"

          echo "Runner.ipa created successfully at $IPA_OUTPUT"

    artifacts:
      - build/Runner.ipa
      - ios/Podfile.lock

    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
