workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      vars:
        HOMEBREW_NO_AUTO_UPDATE: 1
        HOMEBREW_NO_ANALYTICS: 1
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/Homebrew
    scripts:
      # 1. CÀI COCOAPODS TỪ HOMEBREW
      - name: Install CocoaPods
        script: |
          brew install cocoapods
          export PATH="/opt/homebrew/bin:$PATH"
          pod --version

      # 2. CLEAN PROJECT
      - name: Clean Project
        script: |
          export PATH="/opt/homebrew/bin:$PATH"
          flutter clean
          flutter pub get
          rm -rf ios/Pods ios/Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      # 3. CÀI PODS RIÊNG (DÙNG ĐƯỜNG DẪN TUYỆT ĐỐI)
      - name: Install Pods Manually
        script: |
          export PATH="/opt/homebrew/bin:$PATH"
          cd ios
          /opt/homebrew/bin/pod install --verbose
          cd ..

      # 4. BUILD IOS (BỎ QUA COCOAPODS CỦA FLUTTER)
      - name: Build iOS (Skip CocoaPods)
        script: |
          export PATH="/opt/homebrew/bin:$PATH"
          flutter build ios --release --no-codesign --no-cocoapods --verbose

      # 5. PACKAGE IPA
      - name: Package IPA
        script: |
          mkdir -p Payload
          cp -R build/ios/Release-iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload
          rm -rf Payload
          mv Runner.ipa build/

    artifacts:
      - build/Runner.ipa
      - ios/Podfile.lock

    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
