workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      vars:
        HOMEBREW_NO_AUTO_UPDATE: 1
        HOMEBREW_NO_ANALYTICS: 1
        COCOAPODS_DISABLE_DETERMINISTIC_UUIDS: 1
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/Homebrew
        - $HOME/.gem
    scripts:
      # 1. CÀI COCOAPODS + FORCE LINK + FIX PATH
      - name: Install CocoaPods (FORCE LINK)
        script: |
          brew install cocoapods
          brew link --force cocoapods
          
          # Fix PATH ngay lập tức
          export PATH="/opt/homebrew/bin:$PATH"
          echo $PATH | tr ':' '\n' | grep pod
          
          # Kiểm tra
          which pod || echo "POD NOT FOUND"
          pod --version

      # 2. CÀI FFI PURE RUBY
      - name: Install ffi (pure Ruby)
        script: |
          export PATH="/opt/homebrew/bin:$PATH"
          gem uninstall ffi -a -x || true
          gem install ffi --platform=ruby -- --disable-system-libffi

      # 3. CLEAN PROJECT
      - name: Clean Project
        script: |
          export PATH="/opt/homebrew/bin:$PATH"
          flutter clean
          flutter pub get
          rm -rf ios/Pods ios/Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      # 4. CÀI PODS (DÙNG ĐƯỜNG DẪN TUYỆT ĐỐI)
      - name: Install Pods
        script: |
          export PATH="/opt/homebrew/bin:$PATH"
          cd ios
          /opt/homebrew/bin/pod repo update
          /opt/homebrew/bin/pod install --verbose
          cd ..

      # 5. BUILD IOS
      - name: Build iOS
        script: |
          export PATH="/opt/homebrew/bin:$PATH"
          flutter build ios --release --no-codesign --verbose

      # 6. PACKAGE IPA
      - name: Package IPA
        script: |
          mkdir -p Payload
          cp -R build/ios/Release-iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload
          rm -rf Payload
          mv Runner.ipa build/

    artifacts:
      - build/Runner.ipa
      - ios/Podfile.lock

    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
