workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Clean Flutter & Cocoapods
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -f ios/Podfile.lock
          export COCOAPODS_DISABLE_STATS=true

      - name: Install Pods using CDN (Apple Silicon safe)
        script: |
          cd ios
          sudo arch -x86_64 gem install ffi
          arch -x86_64 pod install --repo-update
          cd ..

      - name: Build iOS (no code sign)
        script: flutter build ios --release --no-codesign --verbose

      - name: Package IPA
        script: |
          mkdir -p build/ios/ipa/Payload
          cp -R build/ios/Release-iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r Runner.ipa Payload
          mv Runner.ipa ../../Runner.ipa
          cd ../../..

    artifacts:
      - build/Runner.ipa
