workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      vars:
        HOMEBREW_NO_AUTO_UPDATE: 1
        HOMEBREW_NO_ANALYTICS: 1
        # Bắt buộc: tắt ffi
        COCOAPODS_DISABLE_DETERMINISTIC_UUIDS: 1
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/Homebrew
    scripts:
      # 1. Cài CocoaPods từ Homebrew (KHÔNG dùng gem)
      - name: Install CocoaPods (Homebrew)
        script: |
          brew install cocoapods
          pod --version

      # 2. Patch ffi (bắt buộc để tránh crash)
      - name: Patch ffi gem
        script: |
          # Xóa ffi cũ
          gem uninstall ffi -a -x || true
          # Cài ffi không native (pure Ruby)
          gem install ffi --platform=ruby -- --disable-system-libffi
          echo "FFI installed (pure Ruby)"

      # 3. Clean project
      - name: Clean Project
        script: |
          flutter clean
          flutter pub get
          rm -rf ios/Pods ios/Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      # 4. Install Pods
      - name: Install Pods
        script: |
          cd ios
          pod repo update
          pod install --verbose
          cd ..

      # 5. Build iOS (no codesign)
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign --verbose

      # 6. Package IPA
      - name: Package IPA
        script: |
          mkdir -p Payload
          cp -R build/ios/Release-iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload
          rm -rf Payload
          mv Runner.ipa build/

    artifacts:
      - build/Runner.ipa
      - ios/Podfile.lock
    publishing:
      email:
        recipients:
          - your-email@example.com
