workflows:
  ios-unsigned:
    name: iOS Unsigned Build (Optimized for M2)
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      vars:
        HOMEBREW_NO_AUTO_UPDATE: 1
        HOMEBREW_NO_ANALYTICS: 1
        COCOAPODS_DISABLE_DETERMINISTIC_UUIDS: 1
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/Homebrew
        - $HOME/.gem
    scripts:
      # 1. CÀI COCOAPODS TỪ HOMEBREW (AN TOÀN NHẤT)
      # Đây là phương pháp ổn định trên M-series.
      - name: Install CocoaPods (Homebrew)
        script: |
          brew install cocoapods
          echo "CocoaPods: $(pod --version)"

      # 2. CÀI FFI PURE RUBY (GIẢI PHÁP CHO M2)
      # Giúp tránh lỗi biên dịch các Native Extension của Ruby Gem.
      - name: Install ffi (pure Ruby)
        script: |
          gem uninstall ffi -a -x || true
          gem install ffi --platform=ruby -- --disable-system-libffi
          echo "FFI installed (pure Ruby)"

      # 3. CLEAN PROJECT
      - name: Clean Project
        script: |
          flutter clean
          flutter pub get
          # Xóa Pods/DerivedData để đảm bảo không còn tệp cache cũ gây lỗi
          rm -rf ios/Pods ios/Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      # 4. INSTALL PODS
      - name: Install Pods
        script: |
          cd ios
          # pod repo update chỉ cần thiết nếu bạn gặp lỗi không tìm thấy spec.
          # pod repo update 
          pod install --verbose
          cd ..

      # 5. BUILD IPA (SỬ DỤNG LỆNH CHÍNH THỨC VÀ KIẾN TRÚC RÕ RÀNG)
      - name: Build IPA
        script: |
          # Dùng flutter build ipa thay vì build ios + manual zip.
          # Thêm --target-platform=ios-arm64 để cố định kiến trúc build cho M2.
          flutter build ipa --release --no-codesign --target-platform=ios-arm64 --verbose

    artifacts:
      # Thay đổi path vì giờ chúng ta dùng flutter build ipa
      - build/ios/ipa/*.ipa
      - ios/Podfile.lock
      - build/ios/archive/Runner.xcarchive

    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
