workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      vars:
        HOMEBREW_NO_AUTO_UPDATE: 1
        HOMEBREW_NO_ANALYTICS: 1
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/Homebrew
        - ios/Pods
        - ios/Podfile.lock
        - ios/Flutter/Generated.xcconfig
    scripts:
      # 1. CÀI COCOAPODS
      - name: Install CocoaPods
        script: |
          brew install cocoapods
          export PATH="/opt/homebrew/bin:$PATH"
          pod --version

      # 2. CLEAN & PUB GET
      - name: Flutter Pub Get
        script: |
          export PATH="/opt/homebrew/bin:$PATH"
          flutter pub get

      # 3. CÀI PODS (LUÔN CHẠY 1 LẦN)
      - name: Install Pods
        script: |
          export PATH="/opt/homebrew/bin:$PATH"
          cd ios
          /opt/homebrew/bin/pod install --verbose
          cd ..

      # 4. BUILD BẰNG XCODEBUILD (BỎ QUA FLUTTER TOOLS)
      - name: Build with xcodebuild
        script: |
          export PATH="/opt/homebrew/bin:$PATH"
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -derivedDataPath build \
                     -allowProvisioningUpdates \
                     -quiet \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO
          cd ..

      # 5. PACKAGE IPA
      - name: Package IPA
        script: |
          mkdir -p Payload
          cp -R ios/build/Build/Products/Release-iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload
          rm -rf Payload
          mv Runner.ipa build/

    artifacts:
      - build/Runner.ipa

    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
