workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      vars:
        HOMEBREW_NO_AUTO_UPDATE: 1
        HOMEBREW_NO_ANALYTICS: 1
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/Homebrew
        - $HOME/.gem
    scripts:
      # 1. Cài Homebrew packages (an toàn cho M2)
      - name: Install Homebrew deps
        script: |
          brew install cocoapods ffi
          echo "CocoaPods version: $(pod --version)"
          echo "FFI version: $(gem list ffi | grep ffi)"

      # 2. Clean project
      - name: Clean Flutter & iOS
        script: |
          flutter clean
          flutter pub get
          rm -rf ios/Pods ios/Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      # 3. Install Pods
      - name: Install CocoaPods
        script: |
          cd ios
          pod repo update
          pod install --verbose
          cd ..

      # 4. Build iOS
      - name: Build iOS (no codesign)
        script: |
          flutter build ios --release --no-codesign --verbose

      # 5. Package IPA
      - name: Package IPA
        script: |
          mkdir -p Payload
          cp -R build/ios/Release-iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload
          rm -rf Payload
          mv Runner.ipa build/

    artifacts:
      - build/Runner.ipa
      - ios/Podfile.lock
      - flutter.log
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
