workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      vars:
        HOMEBREW_NO_AUTO_UPDATE: 1
        HOMEBREW_NO_ANALYTICS: 1
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/Homebrew
        - ios/Pods
        - ios/Podfile.lock
    scripts:
      # 1. CÀI COCOAPODS
      - name: Install CocoaPods
        script: |
          brew install cocoapods
          export PATH="/opt/homebrew/bin:$PATH"
          pod --version

      # 2. CLEAN (NHƯNG GIỮ LẠI PODS & PODFILE.LOCK)
      - name: Clean (Keep Pods)
        script: |
          export PATH="/opt/homebrew/bin:$PATH"
          flutter clean
          flutter pub get
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      # 3. CÀI PODS (CHỈ CHẠY NẾU CHƯA CÓ)
      - name: Install Pods (If Needed)
        script: |
          export PATH="/opt/homebrew/bin:$PATH"
          cd ios
          if [ ! -f "Podfile.lock" ]; then
            echo "Podfile.lock not found → Running pod install"
            /opt/homebrew/bin/pod install --verbose
          else
            echo "Podfile.lock exists → Skipping pod install"
          fi
          cd ..

      # 4. BUILD IOS (BỎ QUA POD INSTALL)
      - name: Build iOS (Skip Pod Install)
        script: |
          export PATH="/opt/homebrew/bin:$PATH"
          flutter build ios --release --no-codesign --verbose

      # 5. PACKAGE IPA
      - name: Package IPA
        script: |
          mkdir -p Payload
          cp -R build/ios/Release-iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload
          rm -rf Payload
          mv Runner.ipa build/

    artifacts:
      - build/Runner.ipa
      - ios/Podfile.lock

    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
