class Country {
  final String value;
  final String name;

  const Country(this.value, this.name);

  @override
  String toString() => 'value="$value" $name';
}

final List<Country> countries = [
  const Country("0", "Chọn quốc gia"),
  const Country("1", "United States"),
  const Country("2", "Canada"),
  const Country("3", "Afghanistan"),
  const Country("4", "Albania"),
  const Country("5", "Algeria"),
  const Country("6", "American Samoa"),
  const Country("7", "Andorra"),
  const Country("8", "Angola"),
  const Country("9", "Anguilla"),
  const Country("10", "Antarctica"),
  const Country("11", "Antigua and/or Barbuda"),
  const Country("12", "Argentina"),
  const Country("13", "Armenia"),
  const Country("14", "Aruba"),
  const Country("15", "Australia"),
  const Country("16", "Austria"),
  const Country("17", "Azerbaijan"),

  const Country("18", "Bahamas"),
  const Country("19", "Bahrain"),
  const Country("20", "Bangladesh"),
  const Country("21", "Barbados"),
  const Country("22", "Belarus"),
  const Country("23", "Belgium"),
  const Country("24", "Belize"),
  const Country("25", "Benin"),
  const Country("26", "Bermuda"),
  const Country("27", "Bhutan"),
  const Country("28", "Bolivia"),
  const Country("29", "Bosnia and Herzegovina"),
  const Country("30", "Botswana"),
  const Country("31", "Bouvet Island"),
  const Country("32", "Brazil"),
  const Country("34", "Brunei Darussalam"),
  const Country("35", "Bulgaria"),
  const Country("36", "Burkina Faso"),
  const Country("37", "Burundi"),

  const Country("38", "Cambodia"),
  const Country("39", "Cameroon"),
  const Country("40", "Cape Verde"),
  const Country("41", "Cayman Islands"),
  const Country("42", "Central African Republic"),
  const Country("43", "Chad"),
  const Country("44", "Chile"),
  const Country("45", "China"),
  const Country("46", "Christmas Island"),
  const Country("47", "Cocos (Keeling) Islands"),
  const Country("48", "Colombia"),
  const Country("49", "Comoros"),
  const Country("50", "Congo"),
  const Country("51", "Cook Islands"),
  const Country("52", "Costa Rica"),
  const Country("53", "Croatia (Hrvatska)"),
  const Country("54", "Cuba"),
  const Country("55", "Cyprus"),
  const Country("56", "Czech Republic"),

  const Country("57", "Denmark"),
  const Country("58", "Djibouti"),
  const Country("59", "Dominica"),
  const Country("60", "Dominican Republic"),

  const Country("61", "East Timor"),
  const Country("62", "Ecuador"),
  const Country("63", "Egypt"),
  const Country("64", "El Salvador"),
  const Country("65", "Equatorial Guinea"),
  const Country("66", "Eritrea"),
  const Country("67", "Estonia"),
  const Country("68", "Ethiopia"),

  const Country("69", "Falkland Islands (Malvinas)"),
  const Country("70", "Faroe Islands"),
  const Country("71", "Fiji"),
  const Country("72", "Finland"),
  const Country("73", "France"),
  const Country("74", "France, Metropolitan"),
  const Country("75", "French Guiana"),
  const Country("76", "French Polynesia"),
  const Country("77", "French Southern Territories"),

  const Country("78", "Gabon"),
  const Country("79", "Gambia"),
  const Country("80", "Georgia"),
  const Country("81", "Germany"),
  const Country("82", "Ghana"),
  const Country("83", "Gibraltar"),
  const Country("84", "Greece"),
  const Country("85", "Greenland"),
  const Country("86", "Grenada"),
  const Country("87", "Guadeloupe"),
  const Country("88", "Guam"),
  const Country("89", "Guatemala"),
  const Country("90", "Guinea"),
  const Country("91", "Guinea-Bissau"),
  const Country("92", "Guyana"),

  const Country("93", "Haiti"),
  const Country("94", "Heard and Mc Donald Islands"),
  const Country("95", "Honduras"),
  const Country("96", "Hong Kong"),
  const Country("97", "Hungary"),

  const Country("98", "Iceland"),
  const Country("99", "India"),
  const Country("100", "Indonesia"),
  const Country("101", "Iran (Islamic Republic of)"),
  const Country("102", "Iraq"),
  const Country("103", "Ireland"),
  const Country("104", "Israel"),
  const Country("105", "Italy"),
  const Country("106", "Ivory Coast"),

  const Country("107", "Jamaica"),
  const Country("108", "Japan"),
  const Country("109", "Jordan"),

  const Country("110", "Kazakhstan"),
  const Country("111", "Kenya"),
  const Country("112", "Kiribati"),
  const Country("113", "Korea, Democratic People's Republic of"),
  const Country("114", "Korea, Republic of"),
  const Country("115", "Kosovo"),
  const Country("116", "Kuwait"),
  const Country("117", "Kyrgyzstan"),

  const Country("118", "Lao People's Democratic Republic"),
  const Country("119", "Latvia"),
  const Country("120", "Lebanon"),
  const Country("121", "Lesotho"),
  const Country("122", "Liberia"),
  const Country("123", "Libyan Arab Jamahiriya"),
  const Country("124", "Liechtenstein"),
  const Country("125", "Lithuania"),
  const Country("126", "Luxembourg"),

  const Country("127", "Macau"),
  const Country("128", "Macedonia"),
  const Country("129", "Madagascar"),
  const Country("130", "Malawi"),
  const Country("131", "Malaysia"),
  const Country("132", "Maldives"),
  const Country("133", "Mali"),
  const Country("134", "Malta"),
  const Country("135", "Marshall Islands"),
  const Country("136", "Martinique"),
  const Country("137", "Mauritania"),
  const Country("138", "Mauritius"),
  const Country("139", "Mayotte"),
  const Country("140", "Mexico"),
  const Country("141", "Micronesia, Federated States of"),
  const Country("142", "Moldova, Republic of"),
  const Country("143", "Monaco"),
  const Country("144", "Mongolia"),
  const Country("145", "Montenegro"),
  const Country("146", "Montserrat"),
  const Country("147", "Morocco"),
  const Country("148", "Mozambique"),
  const Country("149", "Myanmar"),

  const Country("150", "Namibia"),
  const Country("151", "Nauru"),
  const Country("152", "Nepal"),
  const Country("153", "Netherlands"),
  const Country("154", "Netherlands Antilles"),
  const Country("155", "New Caledonia"),
  const Country("156", "New Zealand"),
  const Country("157", "Nicaragua"),
  const Country("158", "Niger"),
  const Country("159", "Nigeria"),
  const Country("160", "Niue"),
  const Country("161", "Norfolk Island"),
  const Country("162", "Northern Mariana Islands"),
  const Country("163", "Norway"),

  const Country("164", "Oman"),
  const Country("165", "Pakistan"),
  const Country("166", "Palau"),
  const Country("167", "Panama"),
  const Country("168", "Papua New Guinea"),
  const Country("169", "Paraguay"),
  const Country("170", "Peru"),
  const Country("171", "Philippines"),
  const Country("172", "Pitcairn"),
  const Country("173", "Poland"),
  const Country("174", "Portugal"),
  const Country("175", "Puerto Rico"),
  const Country("176", "Qatar"),
  const Country("177", "Reunion"),
  const Country("178", "Romania"),
  const Country("179", "Russian Federation"),
  const Country("180", "Rwanda"),
  const Country("181", "Saint Kitts and Nevis"),
  const Country("182", "Saint Lucia"),
  const Country("183", "Saint Vincent and the Grenadines"),
  const Country("184", "Samoa"),
  const Country("185", "San Marino"),
  const Country("186", "Sao Tome and Principe"),
  const Country("187", "Saudi Arabia"),
  const Country("188", "Senegal"),
  const Country("189", "Serbia"),
  const Country("190", "Seychelles"),
  const Country("191", "Sierra Leone"),
  const Country("192", "Singapore"),
  const Country("193", "Slovakia"),
  const Country("194", "Slovenia"),
  const Country("195", "Solomon Islands"),
  const Country("196", "Somalia"),
  const Country("197", "South Africa"),
  const Country("198", "South Georgia South Sandwich Islands"),
  const Country("199", "Spain"),
  const Country("200", "Sri Lanka"),
  const Country("201", "St. Helena"),
  const Country("202", "St. Pierre and Miquelon"),
  const Country("203", "Sudan"),
  const Country("204", "Suriname"),
  const Country("205", "Svalbarn and Jan Mayen Islands"),
  const Country("206", "Swaziland"),
  const Country("207", "Sweden"),
  const Country("208", "Switzerland"),
  const Country("209", "Syrian Arab Republic"),
  const Country("210", "Taiwan"),
  const Country("211", "Tajikistan"),
  const Country("212", "Tanzania, United Republic of"),
  const Country("213", "Thailand"),
  const Country("214", "Togo"),
  const Country("215", "Tokelau"),
  const Country("216", "Tonga"),
  const Country("217", "Trinidad and Tobago"),
  const Country("218", "Tunisia"),
  const Country("219", "Turkey"),
  const Country("220", "Turkmenistan"),
  const Country("221", "Turks and Caicos Islands"),
  const Country("222", "Tuvalu"),
  const Country("223", "Uganda"),
  const Country("224", "Ukraine"),
  const Country("225", "United Arab Emirates"),
  const Country("226", "United Kingdom"),
  const Country("227", "United States minor outlying islands"),
  const Country("228", "Uruguay"),
  const Country("229", "Uzbekistan"),
  const Country("230", "Vanuatu"),
  const Country("231", "Vatican City State"),
  const Country("232", "Venezuela"),
  const Country("233", "Vietnam"),
  const Country("238", "Yemen"),
  const Country("239", "Yugoslavia"),
  const Country("240", "Zaire"),
  const Country("241", "Zambia"),
  const Country("242", "Zimbabwe"),
  const Country("243", "Palestine"),
];