// lib/features/social/constants/family_relationships.dart

/// LABEL fallback tiếng Anh (dùng nếu chưa có dịch)
const Map<String, String> kFamilyTypeLabelsEn = {
  '1': 'Mother',
  '2': 'Father',
  '3': 'Daughter',
  '4': 'Son',
  '5': 'Sister',
  '6': 'Brother',
  '7': 'Auntie',
  '8': 'Uncle',
  '9': 'Niece',
  '10': 'Nephew',
  '11': 'Cousin (female)',
  '12': 'Cousin (male)',
  '13': 'Grandmother',
  '14': 'Grandfather',
  '15': 'Granddaughter',
  '16': 'Grandson',
  '17': 'Stepsister',
  '18': 'Stepbrother',
  '19': 'Stepmother',
  '20': 'Stepfather',
  '21': 'Stepdaughter',
  '22': 'Sister-in-law',
  '23': 'Brother-in-law',
  '24': 'Mother-in-law',
  '25': 'Father-in-law',
  '26': 'Daughter-in-law',
  '27': 'Son-in-law',
  '28': 'Sibling (gender neutral)',
  '29': 'Parent (gender neutral)',
  '30': 'Child (gender neutral)',
  '31': 'Sibling of Parent (gender neutral)',
  '32': 'Child of Sibling (gender neutral)',
  '33': 'Cousin (gender neutral)',
  '34': 'Grandparent (gender neutral)',
  '35': 'Grandchild (gender neutral)',
  '36': 'Step-sibling (gender neutral)',
  '37': 'Step-parent (gender neutral)',
  '38': 'Stepchild (gender neutral)',
  '39': 'Sibling-in-law (gender neutral)',
  '40': 'Parent-in-law (gender neutral)',
  '41': 'Child-in-law (gender neutral)',
};

/// KEY dùng để dịch qua getTranslated()
///
/// 👉 Thêm các key này vào file JSON ngôn ngữ (vi/en…)
const Map<String, String> kFamilyTypeTranslationKeys = {
  '1': 'family_mother',
  '2': 'family_father',
  '3': 'family_daughter',
  '4': 'family_son',
  '5': 'family_sister',
  '6': 'family_brother',
  '7': 'family_auntie',
  '8': 'family_uncle',
  '9': 'family_niece',
  '10': 'family_nephew',
  '11': 'family_cousin_female',
  '12': 'family_cousin_male',
  '13': 'family_grandmother',
  '14': 'family_grandfather',
  '15': 'family_granddaughter',
  '16': 'family_grandson',
  '17': 'family_stepsister',
  '18': 'family_stepbrother',
  '19': 'family_stepmother',
  '20': 'family_stepfather',
  '21': 'family_stepdaughter',
  '22': 'family_sister_in_law',
  '23': 'family_brother_in_law',
  '24': 'family_mother_in_law',
  '25': 'family_father_in_law',
  '26': 'family_daughter_in_law',
  '27': 'family_son_in_law',
  '28': 'family_sibling_neutral',
  '29': 'family_parent_neutral',
  '30': 'family_child_neutral',
  '31': 'family_sibling_of_parent_neutral',
  '32': 'family_child_of_sibling_neutral',
  '33': 'family_cousin_neutral',
  '34': 'family_grandparent_neutral',
  '35': 'family_grandchild_neutral',
  '36': 'family_step_sibling_neutral',
  '37': 'family_step_parent_neutral',
  '38': 'family_stepchild_neutral',
  '39': 'family_sibling_in_law_neutral',
  '40': 'family_parent_in_law_neutral',
  '41': 'family_child_in_law_neutral',
};
